ASPWebpage/Models/Asp.cs
namespace ASPWebpage.Models
{
    public class Asp
    {
        public int Id{ get; set; }
        public string Jockquestion { get; set; }
        public string Jockanswer { get; set; }

        public Asp()
        {

        }

    }
}

ASPWebpage/Models/ErrorViewModel.cs
namespace ASPWebpage.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ASPWebpage/Controllers/AspsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ASPWebpage.Data;
using ASPWebpage.Models;

namespace ASPWebpage.Controllers
{
    public class AspsController : Controller
    {
        private readonly ASPWebpageApplicationDbContext _context;

        public AspsController(ASPWebpageApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Asps
        public async Task<IActionResult> Index()
        {
            return View(await _context.Asp.ToListAsync());
        }


        // GET: Asps searchform
        public async Task<IActionResult> ShowearchForm()
        {
            return View("ShowearchForm");
        }

        // Post: Asps searchResult
        public async Task<IActionResult> ShowSearchResult(string SearchPhrase)
        {
            return View("Index", await _context.Asp.ToListAsync());
        }
        // GET: Asps/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var asp = await _context.Asp
                .FirstOrDefaultAsync(m => m.Id == id);
            if (asp == null)
            {
                return NotFound();
            }

            return View(asp);
        }

        // GET: Asps/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Asps/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Jockquestion,Jockanswer")] Asp asp)
        {
            if (ModelState.IsValid)
            {
                _context.Add(asp);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(asp);
        }

        // GET: Asps/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var asp = await _context.Asp.FindAsync(id);
            if (asp == null)
            {
                return NotFound();
            }
            return View(asp);
        }

        // POST: Asps/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Jockquestion,Jockanswer")] Asp asp)
        {
            if (id != asp.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(asp);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AspExists(asp.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(asp);
        }

        // GET: Asps/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var asp = await _context.Asp
                .FirstOrDefaultAsync(m => m.Id == id);
            if (asp == null)
            {
                return NotFound();
            }

            return View(asp);
        }

        // POST: Asps/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var asp = await _context.Asp.FindAsync(id);
            _context.Asp.Remove(asp);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AspExists(int id)
        {
            return _context.Asp.Any(e => e.Id == id);
        }
    }
}

ASPWebpage/Controllers/HomeController.cs
using ASPWebpage.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ASPWebpage.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ASPWebpage/Views/Asps/Create.cshtml
@model ASPWebpage.Models.Asp

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Asp</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Jockquestion" class="control-label"></label>
                <input asp-for="Jockquestion" class="form-control" />
                <span asp-validation-for="Jockquestion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Jockanswer" class="control-label"></label>
                <input asp-for="Jockanswer" class="form-control" />
                <span asp-validation-for="Jockanswer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ASPWebpage/Views/Asps/Delete.cshtml
@model ASPWebpage.Models.Asp

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Asp</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Jockquestion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Jockquestion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Jockanswer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Jockanswer)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ASPWebpage/Views/Asps/Details.cshtml
@model ASPWebpage.Models.Asp

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Asp</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Jockquestion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Jockquestion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Jockanswer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Jockanswer)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ASPWebpage/Views/Asps/Edit.cshtml
@model ASPWebpage.Models.Asp

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Asp</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Jockquestion" class="control-label"></label>
                <input asp-for="Jockquestion" class="form-control" />
                <span asp-validation-for="Jockquestion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Jockanswer" class="control-label"></label>
                <input asp-for="Jockanswer" class="form-control" />
                <span asp-validation-for="Jockanswer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ASPWebpage/Views/Asps/Index.cshtml
@model IEnumerable<ASPWebpage.Models.Asp>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Jockquestion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Jockanswer)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Jockquestion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Jockanswer)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

ASPWebpage/Views/Asps/ShowearchForm.cshtml
<h4>Search for a asp</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="ShowSearchResult">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label name="SearchPhrase" class="control-label"></label>
                <input  name="SearchPhrase" class="form-control" />
                 
            </div>
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ASPWebpage/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h4 class="display-4">ASP APPLICATION</h4>
    <p> This is ASP.Net PAGE.</p>
</div>

ASPWebpage/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASPWebpage</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ASPWebpage.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASPWebpage</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Asps" asp-action="Index">Asps</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Asps" asp-action="ShowearchForm">Search</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ASPWebpage - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>